import { ghHeaders, githubToken } from './github';
import type { Finding } from './types';

/**
 * Open a REAL pull request on GitHub carrying the hybrid patch and its proof.
 * Uses the REST API with the configured GITHUB_TOKEN (repo scope required):
 * read base branch → create recrypt/* branch → commit the patched file →
 * open the PR with the battle history + proof bundle in the body.
 */

const API = 'https://api.github.com';

async function gh<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${API}${path}`, {
    ...init,
    headers: { ...ghHeaders(), 'content-type': 'application/json', ...(init?.headers || {}) },
    cache: 'no-store',
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`GitHub ${init?.method || 'GET'} ${path} → ${res.status}: ${body.slice(0, 200)}`);
  }
  return (await res.json()) as T;
}

export interface OpenedPr {
  url: string;
  number: number;
  branch: string;
}

export async function openPullRequest(opts: {
  owner: string;
  repo: string;
  finding: Finding;
}): Promise<OpenedPr> {
  if (!githubToken()) throw new Error('GITHUB_TOKEN not configured');
  const { owner, repo, finding } = opts;
  const a = finding.analysis;
  if (!a) throw new Error('finding has no analysis yet');

  const repoInfo = await gh<{ default_branch: string }>(`/repos/${owner}/${repo}`);
  const base = repoInfo.default_branch;
  const baseRef = await gh<{ object: { sha: string } }>(`/repos/${owner}/${repo}/git/ref/heads/${base}`);

  const branch = `recrypt/pqc-${finding.file.split('/').pop()?.replace(/[^a-zA-Z0-9.-]/g, '-')}-${Date.now().toString(36)}`;
  await gh(`/repos/${owner}/${repo}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseRef.object.sha }),
  });

  // Fetch the existing file's blob SHA on the new branch (needed to update it).
  let existingSha: string | undefined;
  try {
    const existing = await gh<{ sha: string }>(
      `/repos/${owner}/${repo}/contents/${encodeURIComponent(finding.file)}?ref=${branch}`
    );
    existingSha = existing.sha;
  } catch {
    existingSha = undefined; // new file
  }

  await gh(`/repos/${owner}/${repo}/contents/${encodeURIComponent(finding.file)}`, {
    method: 'PUT',
    body: JSON.stringify({
      message: `Hybrid post-quantum migration: ${finding.file} (${finding.algorithm} → ${a.newAlgorithm})`,
      content: Buffer.from(a.patchedCode, 'utf8').toString('base64'),
      branch,
      ...(existingSha ? { sha: existingSha } : {}),
    }),
  });

  const rounds = a.review?.rounds ?? [];
  const flaws = rounds.reduce((n, r) => n + r.issueCount, 0);
  const body = [
    `## Hybrid post-quantum migration — \`${finding.file}\``,
    '',
    `**Algorithm:** ${finding.algorithm} → **${a.newAlgorithm}**`,
    `**Usage:** ${finding.usageType} · **Risk:** ${finding.risk}`,
    '',
    '### Adversarial review',
    rounds.length > 0
      ? rounds.map((r) => `- Round ${r.round}: ${r.issueCount === 0 ? 'no defensible flaws' : `${r.issueCount} flaw(s) found → patch rewritten`}`).join('\n')
      : `- ${a.review?.summary ?? 'policy checks passed'}`,
    flaws > 0 ? `\nThe red-team agent caught **${flaws} flaw(s)** before this PR was opened.` : '',
    '',
    '### Equivalence proofs (executed, not mocked)',
    a.tests.map((t) => `- ${t.passed ? '✅' : '❌'} ${t.name}`).join('\n'),
    '',
    a.digest ? `**Proof bundle SHA-256:** \`${a.digest}\`` : '',
    '',
    '---',
    '_Generated by [Recrypt](https://recrypt-eight.vercel.app) — find, fix, and prove quantum-vulnerable cryptography._',
  ].join('\n');

  const pr = await gh<{ html_url: string; number: number }>(`/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title: `Quantum-safe migration: ${finding.file} → ${a.newAlgorithm}`,
      head: branch,
      base,
      body,
    }),
  });

  return { url: pr.html_url, number: pr.number, branch };
}
