import type { Finding } from './types';
import { unifiedDiff } from './diff';

/**
 * Build the pull request Recrypt would open in the customer's repo: a real
 * git-applyable patch plus a fully-populated PR (branch, commit, body with the
 * proof — review verdict, equivalence tests, tamper-evident digest).
 *
 * In the demo this is generated for download/copy; in production the same object
 * is handed to the GitHub App to open the PR directly on the customer's repo.
 */
export interface PullRequestBundle {
  branch: string;
  title: string;
  commitMessage: string;
  body: string;
  patch: string;
}

export function buildPullRequest(finding: Finding): PullRequestBundle | null {
  const a = finding.analysis;
  if (!a) return null;

  const base = finding.file.split('/').pop() || 'file';
  const branch = `recrypt/pqc-${base.replace(/[^a-zA-Z0-9]+/g, '-').toLowerCase()}-${finding.id.slice(-6)}`;
  const patch = unifiedDiff(finding.fullCode, a.patchedCode, finding.file);

  const title = `Post-quantum: migrate ${finding.algorithm} → ${a.newAlgorithm} in ${finding.file}`;

  const review = a.review;
  const rounds = review?.rounds?.length ?? 0;
  const testsPassed = a.tests.filter((t) => t.passed).length;

  const commitMessage =
    `Migrate ${finding.file} to hybrid post-quantum (${a.newAlgorithm})\n\n` +
    a.changes.map((c) => `- ${c}`).join('\n');

  const body = [
    `## Post-quantum migration — \`${finding.file}\``,
    ``,
    `**Risk:** ${finding.risk}  ·  **Usage:** ${finding.usageType}  ·  **Confidence:** ${finding.confidence}%`,
    ``,
    `Migrates \`${finding.algorithm}\` to **${a.newAlgorithm}**. The classical algorithm keeps running alongside the NIST post-quantum one (hybrid), so existing counterparties keep working during the migration window.`,
    ``,
    `### What changed`,
    ...a.changes.map((c) => `- ${c}`),
    ``,
    `### Assurance (why this is safe to merge)`,
    review
      ? `- 🛡️ **Independent review:** ${review.verdict.replace(/_/g, ' ')}${rounds ? ` after ${rounds} adversarial round${rounds === 1 ? '' : 's'}` : ''} — ${review.summary}`
      : `- 🛡️ Independent review: not available`,
    `- ✅ **Equivalence tests:** ${testsPassed}/${a.tests.length} passed (real ML-DSA-65 / ML-KEM-768 + classical, executed on-host).`,
    a.digest ? `- 🔒 **Proof digest (SHA-256):** \`${a.digest}\`` : ``,
    a.hndl ? `- ⏳ **Exposure:** ${a.hndl.label} — ${a.hndl.detail}` : ``,
    ``,
    `---`,
    `*Generated by Recrypt. Review the diff and CI before merging.*`,
  ]
    .filter((l) => l !== undefined)
    .join('\n');

  return { branch, title, commitMessage, body, patch };
}
